### ISSUE TITLE
tb-profiler: include qc_fail_variants

### ISSUE THREAD

**Issue by LordRust** [Clinical-Genomics-Lund/bonsai-prp#14]
include the failed variants from the tb-profiler json. This enables us to particularly look at minority variants.

Also add a value pipeline-qc : fail or similar to tell bonsai that the variant could be bad. In bonsai there will need to be an accompanying function to manually flag the `qc_fail_variants` as ok if manual inspection judges it to be a valid variant.

**Comment by ryanjameskennedy** [comment]
This issue is linked to jasen's [minority variant issue](https://github.com/genomic-medicine-sweden/jasen/issues/223).
